import express from "express";
import { pool } from "../db/dbconn.js";
import { authenticateToken } from "../middleware/auth-middleware.js";
import { readFileSync, existsSync } from "fs";
import { exec } from "child_process";
import { promisify } from "util";
import { fileURLToPath } from "url";
import { dirname, resolve, join } from "path";

const execAsync = promisify(exec);
const __dirname = dirname(fileURLToPath(import.meta.url));
const BACKEND_ROOT = resolve(__dirname, "..");
const FRONTEND_ROOT = resolve(__dirname, "../../frontend");

const router = express.Router();

const ALLOWED_TABLES = new Set(['blogs', 'users']);

router.get("/schema/:table", async (req, res) => {
    const { table } = req.params;
    if (!ALLOWED_TABLES.has(table)) {
        return res.status(400).json({ message: "Unknown table" });
    }
    try {
        const { rows } = await pool.query(`
            SELECT
                ordinal_position  AS position,
                column_name,
                data_type,
                character_maximum_length,
                is_nullable,
                column_default
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = $1
            ORDER BY ordinal_position
        `, [table]);
        res.json(rows);
    } catch (err) {
        console.error("Schema query error:", err);
        res.status(500).json({ message: "Failed to fetch schema" });
    }
});

router.get("/users", authenticateToken, async (_req, res) => {
    try {
        const { rows } = await pool.query(
            "SELECT id, name, email, role, created_at, updated_at FROM users ORDER BY created_at DESC"
        );
        res.json(rows);
    } catch (err) {
        console.error("Meta users error:", err);
        res.status(500).json({ message: "Failed to fetch users" });
    }
});

// Returns coverage-summary.json for backend and/or frontend (generated by npm run test:coverage)
router.get("/tests/coverage", authenticateToken, (_req, res) => {
    const result = {};
    const backendPath  = join(BACKEND_ROOT,  "coverage", "coverage-summary.json");
    const frontendPath = join(FRONTEND_ROOT, "coverage", "coverage-summary.json");
    if (existsSync(backendPath))  result.backend  = JSON.parse(readFileSync(backendPath,  "utf8"));
    if (existsSync(frontendPath)) result.frontend = JSON.parse(readFileSync(frontendPath, "utf8"));
    res.json(result);
});

// Runs a test suite (backend or frontend) and returns raw output + exit status
router.post("/tests/run", authenticateToken, async (req, res) => {
    const { suite } = req.body;
    if (!["backend", "frontend"].includes(suite)) {
        return res.status(400).json({ message: "suite must be 'backend' or 'frontend'" });
    }
    const cwd = suite === "frontend" ? FRONTEND_ROOT : BACKEND_ROOT;
    try {
        const { stdout, stderr } = await execAsync("npm test", { cwd, timeout: 120_000 });
        res.json({ success: true, output: stdout + stderr });
    } catch (err) {
        // Jest/Vitest exit non-zero on failures — output is still in err.stdout/stderr
        res.json({ success: false, output: (err.stdout || "") + (err.stderr || "") });
    }
});

export default router;
